apiVersion: apps/v1
kind: Deployment
metadata:
  name: datapower-nano-operator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: datapower-nano-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: datapower-nano-operator
    spec:
      containers:
        - name: datapower-nano-operator
          image: {{ include "datapower-nano-operator.image" . }}
          imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
          resources:
            requests:
              cpu: '500m'
              memory: '512Mi'
            limits:
              cpu: 2
              memory: '2Gi'
          env:
            - name: RUST_LOG
              value: dpn_operator=info
            - name: RUST_BACKTRACE
              value: '1'
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          securityContext:
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: 'kubernetes.io/arch'
                    operator: In
                    values: ['amd64']
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: datapower-nano-operator
      hostNetwork: false
      hostPID: false
      hostIPC: false
      serviceAccountName: datapower-nano-operator
      securityContext:
        runAsNonRoot: true
      terminationGracePeriodSeconds: 10
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
